export const reservationUserTable = [
  {
    id: 1,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Dpk12',
    bikeColor: 'Black',
    bikeLocation: 'Lahore',
    averageRating: '2',
    reservation: [
      {
        name: 'Jane Smith',
        email: 'jane@example.com',
        type: 'manager',
        startDate: '2024-06-25T14:00:00',
        endDate: '2024-06-26T14:00:00',
      },
      {
        name: 'Local Smith',
        email: 'local@example.com',
        type: 'user',
        startDate: '2024-06-25T14:00:00',
        endDate: '2024-06-26T14:00:00',
      },
    ],
  },
  {
    id: 2,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Rkt25',
    bikeColor: 'Red',
    bikeLocation: 'Karachi',
    averageRating: '3.5',
    reservation: [
      {
        name: 'John Doe',
        email: 'john@example.com',
        type: 'customer',
        startDate: '2024-06-27T10:00:00',
        endDate: '2024-06-28T10:00:00',
      },
    ],
  },
  {
    id: 3,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Spd20',
    bikeColor: 'Blue',
    bikeLocation: 'Islamabad',
    averageRating: '4.5',
    reservation: [
      {
        name: 'Alice Johnson',
        email: 'alice@example.com',
        type: 'customer',
        startDate: '2024-06-29T09:00:00',
        endDate: '2024-06-30T09:00:00',
      },
    ],
  },
  {
    id: 4,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Mtb15',
    bikeColor: 'Green',
    bikeLocation: 'Quetta',
    averageRating: '4',
    reservation: [
      {
        name: 'Bob Brown',
        email: 'bob@example.com',
        type: 'customer',
        startDate: '2024-07-01T08:00:00',
        endDate: '2024-07-02T08:00:00',
      },
    ],
  },
  {
    id: 5,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Crb30',
    bikeColor: 'Yellow',
    bikeLocation: 'Faisalabad',
    averageRating: '3',
    reservation: [
      {
        name: 'Charlie Davis',
        email: 'charlie@example.com',
        type: 'customer',
        startDate: '2024-07-03T07:00:00',
        endDate: '2024-07-04T07:00:00',
      },
    ],
  },
  {
    id: 6,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Bmx40',
    bikeColor: 'Orange',
    bikeLocation: 'Multan',
    averageRating: '2.5',
    reservation: [
      {
        name: 'David Evans',
        email: 'david@example.com',
        type: 'customer',
        startDate: '2024-07-05T06:00:00',
        endDate: '2024-07-06T06:00:00',
      },
    ],
  },
  {
    id: 7,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Trk50',
    bikeColor: 'Purple',
    bikeLocation: 'Rawalpindi',
    averageRating: '3.5',
    reservation: [
      {
        name: 'Eve Foster',
        email: 'eve@example.com',
        type: 'customer',
        startDate: '2024-07-07T05:00:00',
        endDate: '2024-07-08T05:00:00',
      },
    ],
  },
  {
    id: 8,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Grv60',
    bikeColor: 'Pink',
    bikeLocation: 'Peshawar',
    averageRating: '4.8',
    reservation: [
      {
        name: 'Frank Green',
        email: 'frank@example.com',
        type: 'customer',
        startDate: '2024-07-09T04:00:00',
        endDate: '2024-07-10T04:00:00',
      },
    ],
  },
  {
    id: 9,
    createdAt: '',
    updatedAt: '',
    bikeModal: 'Cty70',
    bikeColor: 'White',
    bikeLocation: 'Hyderabad',
    averageRating: '4.2',
    reservation: [
      {
        name: 'Grace Hall',
        email: 'grace@example.com',
        type: 'customer',
        startDate: '2024-07-11T03:00:00',
        endDate: '2024-07-12T03:00:00',
      },
    ],
  },
];
