#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run pre-commit
npm run lintfix  
git fetch
git update-index --again
if [ ! -z "$(git rev-list ..dev)" ]
then
    echo "abandoning commit"
    echo "please merge from dev and try again"
    exit 1
fi
